### ISSUE TITLE
T2: Create UI 1/2

### ISSUE THREAD

**Issue by aleyna-yildizli** [aleyna-yildizli/aleyna-ecommerce#2]
- Create Figma Designs: [Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community)](https://www.figma.com/file/tXhNJv706AWM0lXlyxLH9l/E-commerce-UI---Figma-Ecommerce-UI-Kit-(Demo-Version)-(Community))
- Use only **Flex** Layout
- Use only **Tailwind classes, no custom classes allowed!**
    - Check **Customizing Theme and Arbitrary** [values on Tailwind](https://tailwindcss.com/docs/adding-custom-styles#using-arbitrary-values)
    - Check **@apply** [directive usage on Tailwind](https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply)

- [x] Create Layout Components like: **Header, PageContent,  Footer 
NOTE! There should be only ONE Header, Footer components for all pages, no color changes needed!**

Create Page Components (**Only Desktop Views**): **Home, Product List**
- [x] Create repetitive Components like: **ProductCard, CategoryCard**
- [x] Home Page: Slider component
    - [x] Find a slider component can be used in React JS
- [x] Activate **React Router and Links** for Home and Shopping links
- [x] Use an **Icon Library** like: FontAwesome (CDN is recommended)

**Comment by aleyna-yildizli** [comment]
Layouts created.

**Comment by aleyna-yildizli** [comment]
I finished all of it except the Practical Suggestions component.

**Comment by aleyna-yildizli** [comment]
T2 is over. The question I want to ask is, I implemented the mapping function in the FeaturedPosts component for google, trending and new. When it is a custom pointer, the colors change, but the color changes on every card, not just a single card. I don't know how to solve the problem.

![Image](https://github.com/aleyna-yildizli/aleyna-ecommerce/assets/152474292/f84ad695-5bc8-42c9-9a88-29d5798f230c)

**Comment by aleyna-yildizli** [comment]
@gokhanozdemir

**Comment by gokhanozdemir** [comment]
Its possible to create an array of matching colors for ex pastel 

- https://rgbcolorpicker.com/random
- https://huemint.com/
then randomly select 
perhaps you can extract that functiojality to a hook and run it as the tag or similar component renders.
