### ISSUE TITLE
T4: Make Responsive

### ISSUE THREAD

**Issue by aleyna-yildizli** [aleyna-yildizli/aleyna-ecommerce#4]
In figma design there are also mobile views. **Mobile views** should be implemented to all pages:
    - [x] Home
    - [ ] Shopping
    - [ ] Product
    - [ ] About
    - [ ] Team
    - [ ] Contac
- [ ] [**CHECK Tailwind responsive solution:**](https://tailwindcss.com/docs/responsive-design)
- [ ] [**CHECK Tailwind switch breakpoints min to max responsive solution:**](https://tailwindcss.com/docs/screens#max-width-breakpoints)

**Comment by aleyna-yildizli** [comment]
Bütün sayfalar responsive hala getirildi, mobile first kullanıldı. @gokhanozdemir kanban task i.erisinde ki checkboxlar çalışmıyor. İyi çalışmalar.

**Comment by gokhanozdemir** [comment]
indentin hatası varmış. yeniden karşılaşırsan, edit deyip, parantezler içine x yazabilirsin
